
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 04 12:39:02 CST 2024
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Nombre = 3;
  public static final int Hombre = 5;
  public static final int Error = 8;
  public static final int EOF = 0;
  public static final int Mesa = 4;
  public static final int Inicio = 2;
  public static final int error = 1;
  public static final int Mujer = 6;
  public static final int Fin = 7;
}

